# ===============================
# Configuración de la Base de Datos
# ===============================

# Host del servidor de base de datos (ej: localhost, 127.0.0.1 o IP/URL remota)
db.host=mismonedas.cps2o2a0qthk.us-east-2.rds.amazonaws.com

# Puerto del servidor de base de datos (ej: 3306 para MySQL, 5432 para PostgreSQL)
db.puerto=3306

# Nombre de la base de datos
db.base=mismonedas

# Usuario con permisos de acceso
db.usuario=admin

# Contraseña del usuario
db.contrasena=LP1Grupo42025
